# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-04-29 05:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_getcontent', '0002_placelist'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseFor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forwhom', models.CharField(db_column='課程對象', max_length=5)),
            ],
            options={
                'db_table': '列表_課程對象',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CourseList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(db_column='課程名稱', max_length=20)),
                ('course_type', models.CharField(db_column='課程類型', max_length=5)),
            ],
            options={
                'db_table': '列表_課程名稱',
                'managed': False,
            },
        ),
        migrations.AlterModelTable(
            name='placelist',
            table='列表_場地',
        ),
        migrations.AlterModelTable(
            name='teacherlist',
            table='列表_教師',
        ),
    ]
