# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-06-26 08:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_getcontent', '0003_auto_20180429_1335'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseNeedToOpen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(db_column='年級', max_length=5)),
                ('mon', models.IntegerField(db_column='Mon')),
                ('tue', models.IntegerField(db_column='Tue')),
                ('wed', models.IntegerField(db_column='Wed')),
                ('thu', models.IntegerField(db_column='Thu')),
                ('fri', models.IntegerField(db_column='Fri')),
            ],
            options={
                'db_table': '排課紀錄_開課數量',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CourseSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(db_column='設定內容', max_length=50)),
                ('value', models.CharField(db_column='設定值', max_length=3)),
            ],
            options={
                'db_table': '排課設定',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OpenCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isEng', models.IntegerField(db_column='英授')),
                ('week', models.IntegerField(db_column='星期')),
                ('time', models.IntegerField(db_column='節次')),
            ],
            options={
                'db_table': '排課紀錄_開設課程',
                'permissions': (('can_open', 'can open courses'), ('can_see', 'can see opened courses'), ('can_modify', 'can modify opened courses'), ('can_delete', 'can delete opened courses')),
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Semester1CourseOfGrade1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dep', models.CharField(db_column='系所', max_length=10)),
                ('week', models.IntegerField(blank=True, db_column='星期', null=True)),
                ('time', models.IntegerField(blank=True, db_column='節次', null=True)),
                ('isEng', models.IntegerField(db_column='英授')),
            ],
            options={
                'db_table': '列表_大一體育',
                'managed': False,
            },
        ),
    ]
