# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-06-26 08:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_getcontent', '0004_courseneedtoopen_coursesetting_opencourse_semester1courseofgrade1'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='opencourse',
            options={'managed': False},
        ),
    ]
